### PR TITLE
fix login button text

### LINKED ISSUE #536: Login form shows "Signing in..." even when button is not clicked
Opening https://omedis.optimum.ba/login shows "Signing in..." button.

Image

 It should be "Sign in" and when it's clicked, then it should be disabled and it should show "Signing in...".

### PR DESCRIPTION
**Pull request by briankariuki**
closes #536

### CODE REVIEW

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Can you add a test for this?

**Comment by briankariuki** [comment]
> Can you add a test for this?

Added

File: test/omedis_web/live/login_test.exs [hunk 1]
```diff
@@ -76,5 +76,22 @@ defmodule OmedisWeb.LoginTest do
...
+      {:ok, user} = Accounts.create_user(@valid_create_params)
+
+      {:ok, lv, html} = live(conn, ~p"/login")
+
+      form =
+        form(lv, "#basic_user_sign_in_form", user: %{email: user.email, password: "password"})
+
+      conn = submit_form(form, conn)
+
+      assert html =~ "Signing in..."
```
Comment (almirsarajcic) [inline test/omedis_web/live/login_test.exs:92]: Even if you put this line before the form submission it's going to pass because that string is always a part of the HTML. What you need to do instead is check that there is a visible element on the page after you render the submit event.

You can use https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#has_element?/3 and https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#render_submit/1 to accomplish this.

**Review by almirsarajcic — CHANGES_REQUESTED** [review]

File: test/omedis_web/live/login_test.exs (hunk 1 above)
Comment (briankariuki) [reply test/omedis_web/live/login_test.exs:92]: I've updated the test

Comment (almirsarajcic) [reply test/omedis_web/live/login_test.exs:97]: It's the same thing because "Signing in..." is always a part of the returned HTML:
https://github.com/3Stones-io/omedis/blob/121c7053247ab27bb50412ec3a376f914dc24469/lib/omedis_web/live/login_live.ex#L131

Try to write a test that will fail before you submit the form.

Comment (briankariuki) [reply test/omedis_web/live/login_test.exs:97]: I've tried using has_element/3 and couldn't get the test to pass. I think the button content is changed via liveview javascript bindings when the button is clicked. I've asked on elixir slack if there is a way to write this kind of test.

```
{:ok, view, _html} = live(conn, ~p"/login")

view
|> form("#basic_user_sign_in_form", user: %{email: user.email, password: "password"})
|> render_submit()

assert has_element?(
         view,
         "button[type=\"submit\"][data-phx-disable-with-restore=\"Sign in\"]"
       )
```

Comment (briankariuki) [reply test/omedis_web/live/login_test.exs]: I've changed the test to check if the button is present in the view.

```
assert has_element?(view, "button[type=\"submit\"]")
```

Comment (almirsarajcic) [reply test/omedis_web/live/login_test.exs]: Yeah, but now you don't assert on the text which was the whole point, I guess.
That's the third argument you should pass to the [`has_element?/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#has_element?/3) function.

If that can't really be achieved in the LiveView, then there's no reason for this test.

Comment (almirsarajcic) [reply test/omedis_web/live/login_test.exs]: Just tried it and you're right. It depends on Javascript so it can't be asserted on inside LiveView tests.
You can remove the test and then let's merge the PR.

Comment (briankariuki) [reply test/omedis_web/live/login_test.exs]: I've removed the test

**Review by almirsarajcic — APPROVED** [review]
