### PR TITLE
Invited users bugfixes

### LINKED ISSUE #424: Invitees should not create an organisation after invitation
@almirsarajcic, @wintermeyer, I noticed that in the current flow, when an invitee accepts an invitation and creates an account, they still have access to create an organisation. There is a rule that only one organisation per user can be created, and the invitee already belongs to an organisation. I think that this is a bug.

https://github.com/user-attachments/assets/3555a2b0-8256-46af-a6c8-85ff503f16e1

### LINKED ISSUE #428: Add invited user to the Users group after registration
Related to https://github.com/3Stones-io/omedis/discussions/427.

When a user is invited, we should give them some access rights so they can see the organisation and its resources.
When an organisation is created, we already create a `Users` group, so we should add the newly created user to that group.

### LINKED ISSUE #430: Fix tests
```
Running ExUnit with seed: 406252, max_cases: 8

................................................................................................................

  1) test by_id/1 returns an error if invitation has expired (Omedis.Accounts.InvitationTest)
Error:      test/omedis/accounts/invitation_test.exs:322
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     code: {:ok, invitation} =
     stacktrace:
       test/omedis/accounts/invitation_test.exs:328: (test)

...........................................

  2) test /organisations/:slug/invitations/:id shows error when user is already registered (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:157
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2

.

  3) test /organisations/:slug/invitations/:id page is displayed in the correct language (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:108
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2

.

  4) test /organisations/:slug/invitations/:id shows error for expired invitation (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:126
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2

.

  5) test /organisations/:slug/invitations/:id form errors are displayed (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:92
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2

..

  6) test /organisations/:slug/invitations/:id shows error for invalid invitation ID (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:142
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2

.....

  7) test /organisations/:slug/invitations/:id invitee with a valid invitation can register for an account (OmedisWeb.InvitationLive.ShowTest)
Error:      test/omedis_web/live/invitation_live/show_test.exs:54
     ** (MatchError) no match of right hand side value: {:error, %Ash.Error.Invalid{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: :expires_at, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}, %Ash.Error.Changes.InvalidChanges{fields: nil, message: "expiration time must be in the future", validation: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :invalid}]}}
     stacktrace:
       test/omedis_web/live/invitation_live/show_test.exs:38: OmedisWeb.InvitationLive.ShowTest.__ex_unit_setup_1/1
       test/omedis_web/live/invitation_live/show_test.exs:1: OmedisWeb.InvitationLive.ShowTest.__ex_unit__/2
```

### PR DESCRIPTION
**Pull request by amos-kibet**
Resolves #424.
Resolves #428.
Resolves #430.

### CODE REVIEW

File: lib/omedis/accounts/checks/invitation_not_expired_filter.ex [hunk 1]
```diff
@@ -10,6 +10,6 @@ defmodule Omedis.Accounts.InvitationNotExpiredFilter do
   end
 
   def filter(_actor, _context, _options) do
-    expr(status != ^:expired or expires_at > ^DateTime.utc_now())
+    expr(status != ^:expired)
```
Comment (almirsarajcic) [inline lib/omedis/accounts/checks/invitation_not_expired_filter.ex:13]: Just to make it clear, this will make invitations still working until the next cron run. I guess that's ok.
No need for any changes, just a confirmation.

**Review by almirsarajcic — CHANGES_REQUESTED** [review]
Unfortunately, there's a merge conflict.
If it was only `coveralls.json`, I'd fix it, but I'm too lazy to deal with translation files too.
Btw., https://github.com/3Stones-io/omedis/issues/431.

Anyway, good job.
🔫🤠

File: lib/omedis/accounts/checks/invitation_not_expired_filter.ex (hunk 1 above)
Comment (amos-kibet) [reply lib/omedis/accounts/checks/invitation_not_expired_filter.ex:13]: That's true. The check for `expires_at` is redundant since we don't allow creating invitations that have `expires_at` value in the past, or now. Here's the check:
```elixir
if expires_at > DateTime.utc_now() do
      changeset
    else
      Ash.Changeset.add_error(changeset, [:expires_at, "expiration time must be in the future"])
end
```

**Comment by amos-kibet** [comment]
> Unfortunately, there's a merge conflict. If it was only `coveralls.json`, I'd fix it, but I'm too lazy to deal with translation files too. Btw., #431.
> 
> Looking at the changes related to `expires_at`, I'd say this fixes #430 too.
> 
> Anyway, good job. 🔫🤠

Yes, it does fixes #430. I have linked it.

**Review by almirsarajcic — APPROVED** [review]
Thanks!

By the way, next time ship the whole MVP in one PR :P
